### ISSUE TITLE
Should 21.0.0.35.1 be marked as "final" release

### ISSUE THREAD

**Issue by bric3** [corretto/corretto-21#21]
It seems that 21.0.0.35.1 is used on the download links on the amazon website, but the release here is still marked as pre-release. (Build 35 was candidate then got GA since there were no P1 bugs)

https://github.com/corretto/corretto-21/releases/tag/21.0.0.35.1

https://github.com/corretto/corretto-downloads/blob/e4a73e49c5fd2b0f1630b39239610884fcf74de3/latest_links/indexmap_with_checksum.json#L1597-L1602

```json
    "21": {
     "pkg": {
      "checksum": "760d89e954093c43907454120eef3c1f",
      "checksum_sha256": "4a877d133a3c2c524947a53f5f031cb87264c18c97c858acb084bbf8bf4e476c",
      "resource": "/downloads/resources/21.0.0.35.1/amazon-corretto-21.0.0.35.1-macosx-aarch64.pkg"
     },
```

**Comment by SentryMan** [comment]
in addition, the docs on the corretto site still have 21 marked as early access.

**Comment by navyxliu** [comment]
hi, @bric3 @SentryMan , 
We haven't officially released jdk-21 yet.

**Comment by SentryMan** [comment]
Why is it highlighted prominently on the front page then? https://aws.amazon.com/corretto/

**Comment by SentryMan** [comment]
Well, I guess the better question is when can we expect it to be officially released?

**Comment by Hc747** [comment]
Will this become available on docker once it hits GA/final?

**Comment by caojoshua** [comment]
> Why is it highlighted prominently on the front page then? https://aws.amazon.com/corretto/

Corretto 21 is available for download, but it is currently in early access. https://docs.aws.amazon.com/corretto/latest/corretto-21-ug/what-is-corretto-21.html

We will be releasing Corretto 21 today in the next few hours. After the GitHub release, it will be available on docker after another few hours.

**Comment by benty-amzn** [comment]
[official-images#15408](https://github.com/docker-library/official-images/pull/15408) is the PR for the dockerhub update. Once that's merged images should be available on dockerhub and ecr gallery within a few hours.

**Comment by SentryMan** [comment]
> We will be releasing Corretto 21 today in the next few hours.

Releasing Java 21 on the 21st... Incredible. I never should have doubted

**Comment by matteobertozzi** [comment]
Is there anything tracking the maven-amazon-corretto21 package? the last available is maven-amazon-corretto17

**Comment by caojoshua** [comment]
I'm not aware of maven-amazon-correttoN package. Where is the package hosted? Don't see it here https://mvnrepository.com/search?q=corretto

**Comment by matteobertozzi** [comment]
> I'm not aware of maven-amazon-correttoN package. Where is the package hosted? Don't see it here https://mvnrepository.com/search?q=corretto

It is something from the amazonlinux repo that configures the default JAVA_HOME in /etc/java/maven.conf 

$ dnf repoquery -i maven-amazon-corretto17
Last metadata expiration check: 0:00:35 ago on Fri Sep 22 16:42:13 2023.
Name         : maven-amazon-corretto17
Epoch        : 1
Version      : 3.8.4
Release      : 3.amzn2023.0.4
Architecture : noarch
Size         : 9.7 k
Source       : maven-3.8.4-3.amzn2023.0.4.src.rpm
Repository   : amazonlinux
Summary      : Amazon Corretto 17 binding for Maven
URL          : https://maven.apache.org/
License      : ASL 2.0 and MIT
Description  : Configures Maven to run with Amazon Corretto 17.

**Comment by stewartsmith** [comment]
> Is there anything tracking the maven-amazon-corretto21 package? the last available is maven-amazon-corretto17

I've opened https://github.com/amazonlinux/amazon-linux-2023/issues/465 to track this.

**Comment by rahulkrvnit** [comment]
expected date of release?

**Comment by SentryMan** [comment]
even though the docs still say it's in early access, they have released it. https://github.com/corretto/corretto-21/releases/tag/21.0.0.35.1

**Comment by rahulkrvnit** [comment]
If released , why is it still asking for confirmation of early release once I start using it?

**Comment by caojoshua** [comment]
Where is it asking for confirmation of early release?

**Comment by daeho-ro** [comment]
I am waiting for this on the IntelliJ jdk list but not yet updated. Any plan?

**Comment by SentryMan** [comment]
You realize this is not the intellij repo?

**Comment by daeho-ro** [comment]
> You realize this is not the intellij repo?

I know that but I am just worried about the release of the new version is not well announced. Should I wait a bit?

**Comment by Rudometov** [comment]
> I am waiting for this on the IntelliJ jdk list but not yet updated. Any plan?

Good point, filed https://youtrack.jetbrains.com/issue/IDEA-333648

**Comment by rgithubli** [comment]
The initial question has already been resolved. Closing.
