### ISSUE TITLE
RPM configuration for "Provides" should include "java"

### ISSUE THREAD

**Issue by g-dx** [corretto/corretto-21#30]
Examination of the RPM for Amazon Corretto 21 hosted here:

https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.rpm

shows that when installed, the dependency is provided under a range of names, most of which start with a `java-21` prefix:

```bash
sh-4.2$ rpm -qp amazon-corretto-21-x64-linux-jdk.rpm --provides
java-21-amazon-corretto-devel = 1:21.0.1.12-1
java-21-devel = 1:21.0.1.12
java-21-openjdk-devel = 1:21.0.1.12-1
java-sdk-21 = 1:21.0.1.12
java-sdk-21-openjdk = 1:21.0.1.12-1
java-21 = 1:21.0.1.12
java-21-openjdk = 1:21.0.1.12
jre = 1:21.0.1.12
jre-21 = 1:21.0.1.12
jre-21-openjdk = 1:21.0.1.12
```
However, `java` is missing from the list meaning any other RPM package which declares a dependency like so:

```
java >= 1:1.8.0
```
cannot be satisfied by the Amazon Corretto 21 RPM dependency. This results in older Java versions being installed.

Can the RPM configuration be updated to include `java` in the `Provides` section?

**Comment by benty-amzn** [comment]
Thanks for reaching out. I've fixed this for Corretto 17, 21, and tip repositories and the fix should go out as part of the 2024-01-16 patch release.

**Comment by g-dx** [comment]
Amazing! Thanks for addressing this so quickly :trophy:
