### ISSUE TITLE
Crash: libjvm.so error

### ISSUE THREAD

**Issue by EpicPlayzGames** [corretto/corretto-21#49]
### Describe the bug
I use Corretto 21 within a docker environment for running a server for Minecraft, I don't know much on java so I'm unsure how to explain what is happening or even how to recreate this. I try to start the server, and it crashes with a given stack trace error for libjvm.so, but will generate different problematic frames each crash.

### To Reproduce
This Corretto 21 image is used within alpine 3.4 in docker in order to run a Minecraft server within Pterodactyl Panel Software, unsure how to reproduce this in any since 

I use this script provided by myself [EpicPlayzGames](https://github.com/EpicPlayzGames/Pterodactyl-Eggs/blob/main/Eggs/Games/Minecraft/GregtechNewHorizons/v2.5.1/egg-gregtech-new-horizons-v2-5-1--alpine.json) on GitHub in order to create the image and use Corretto 21 provided by [Software-Noob](https://github.com/Software-Noob/pterodactyl-images/blob/main/java-corretto/21/Dockerfile) on GitHub specifically for the Pterodactyl Panel Software  

### Platform information
    OS: Amazon Linux 2
    Version Corretto-21.0.2.13.1

### Additional context
Gladly will provide more content as needed, I'm not sure if all the info is here as I was unsure how to report this 
[hs_err_pid1.log](https://github.com/corretto/corretto-21/files/14274151/hs_err_pid1.log)

**Comment by shipilev** [comment]
This looks like a crash when Full GC encounters the array element that points to `0x...8000` address (see `si_addr`). GC tries to follow it, but that pointer leads outside of Java heap (see heap addresses), which is then caught as memory error.

```
Stack: [0x00007fbea0659000,0x00007fbea0759000],  sp=0x00007fbea0756f00,  free space=1015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xc19ac2]  MarkSweep::follow_array_chunk(objArrayOopDesc*, int)+0x262
V  [libjvm.so+0xc19d7f]  MarkSweep::follow_stack()+0xef
...
V  [libjvm.so+0x86cf00]  VM_GenCollectFull::doit()+0x50
...

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000008000

...

Heap:
 def new generation   total 692800K, used 32197K [0x0000000400000000, 0x000000042efb0000, 0x0000000555550000)
  eden space 615872K,   3% used [0x0000000400000000, 0x0000000401358d88, 0x0000000425970000)
  from space 76928K,  16% used [0x0000000425970000, 0x00000004265889c8, 0x000000042a490000)
  to   space 76928K,   0% used [0x000000042a490000, 0x000000042a490000, 0x000000042efb0000)
 tenured generation   total 1539412K, used 1432216K [0x0000000555550000, 0x00000005b34a5000, 0x0000000800000000)
   the space 1539412K,  93% used [0x0000000555550000, 0x00000005acbf6350, 0x00000005acbf6400, 0x00000005b34a5000)
 Metaspace       used 233796K, committed 234880K, reserved 1310720K
  class space    used 36609K, committed 37120K, reserved 1048576K
```

Seeing how close that `0x0000000000008000` is to all zeroes `null`, which would be handled well, I'd first suspect host memory encountered a bit flip. If this happens often, that might be even a non-transient hardware memory error.

Please try to run memtest on that machine and confirm its memory is good?

**Comment by EpicPlayzGames** [comment]
> Seeing how close that `0x0000000000008000` is to all zeroes `null`, which would be handled well, I'd first suspect host memory encountered a bit flip. If this happens often, that might be even a non-transient hardware memory error.
> 
> Please try to run memtest on that machine and confirm its memory is good?

I will be sure to run some tests and get back to you on that today. This specific machine is loaded with 48GB of DDR4 3200MHz if that helps with any specifics.

**Comment by EpicPlayzGames** [comment]
A couple hours and counting. Can confirm it was a ram issue, counted 2537 errors and only 72% done. Safe to say it was likely a hardware issue. Screenshot for reference 

![image](https://github.com/corretto/corretto-21/assets/78707704/0d635ecd-a878-4375-83ee-1401e6b9d58e)

Thanks for the timely comment.
