### ISSUE TITLE
Request backport of JDK-8294699

### ISSUE THREAD

**Issue by lwahonen** [corretto/corretto-21#51]
### Is your feature request related to a problem?

We are committed to running Corretto LTS in production, but hit this bug consistently. Requesting a backport of the fix from JDK 23 branch

**Comment by lwahonen** [comment]
Already backported

**Comment by lutkerd** [comment]
The fix was only backported to Oracle's JDK so far. I have requested this for OpenJDK as well: https://github.com/openjdk/jdk21u-dev/pull/327

**Comment by lutkerd** [comment]
This fix was released in [Corretto 21.0.3.9.1](https://github.com/corretto/corretto-21/releases/tag/21.0.3.9.1). Please update and let us know if you still see the issue.

Thanks.
