### ISSUE TITLE
Crash: SIGSEGV fatal error with problematic frame `V  [libjvm.so+0xf66b09]  ThreadSnapshot::initialize(ThreadsList*, JavaThread*)+0x179`

### ISSUE THREAD

**Issue by l-lin** [corretto/corretto-21#52]
### Describe the bug

I use Corretto 21 within a docker environment and my server crashed with the following error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffa5a51fb09, pid=1, tid=51
#
# JRE version: OpenJDK Runtime Environment Corretto-21.0.2.13.1 (21.0.2+13) (build 21.0.2+13-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-21.0.2.13.1 (21.0.2+13-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xf66b09]  ThreadSnapshot::initialize(ThreadsList*, JavaThread*)+0x179
#
# Core dump will be written. Default location: //core
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-21/issues/
#
```

### To Reproduce

Unfortunately, it crashed rarely (first occurrence for ~20 servers that use the same docker image).

Moreover, there were no end-user activity at the time of the crash.

### Platform information

- Debian 10 x86_64 GNU/Linux
- used amazoncorretto:21-alpine docker image
- Corretto-21.0.2.13.1

### Additional context

[hs_err_pid1.log](https://github.com/corretto/corretto-21/files/14633576/hs_err_pid1.log)

Thanks.

**Comment by Rudometov** [comment]
Have you tried running with the most recent [21.0.2.14.1](https://github.com/corretto/corretto-21/releases/tag/21.0.2.14.1)?

**Comment by l-lin** [comment]
I re-deployed my services with this [21.0.2.14.1](https://github.com/corretto/corretto-21/releases/tag/21.0.2.14.1) version. Will keep in touch if the error is thrown again.

**Comment by l-lin** [comment]
I have not encountered the issue since then. I'm closing the issue.

**Comment by wcwssf** [comment]
> I have not encountered the issue since then. I'm closing the issue.

Hi,Did the problem recur later?

**Comment by l-lin** [comment]
Hello! No, the issue has not occurred again.

**Comment by wcwssf** [comment]
> Hello! No, the issue has not occurred again.

OK, Thanks
