### ISSUE TITLE
 SIGSEGV (0xb) at pc=0x0000000000000eb6, pid=1, tid=44

### ISSUE THREAD

**Issue by Daron95** [corretto/corretto-21#60]
Hello,

I am using Argon2 for hashing in Java , like:

String hashPassword =  argon2.hash(1, 65536, 4, password.toCharArray());

Using Java 19,  all is working well without any issue .

After deploying on Azure using Java Corretto-21.0.2.14.1 , when it reaches the above line, I got the error:

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000eb6, pid=1, tid=44
#
# JRE version: OpenJDK Runtime Environment Corretto-21.0.2.14.1 (21.0.2+14) (build 21.0.2+14-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-21.0.2.14.1 (21.0.2+14-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [jna8976215356681751881.tmp+0x523a]
#
# Core dump will be written. Default location: //core.1
#
# An error report file with more information is saved as:
# //hs_err_pid1.log
[68.376s][warning][os] Loading hsdis library failed
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-21/issues/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by alvdavi** [comment]
Hi, thanks for reaching out. Without the hs_err log file it would be difficult to look into this. However, based on the problematic frame being a tmp file that starts with jna, I believe this is most likely a problem when calling java-native-access. If that is the case, then the SIGSEGV code may have happened on the native code called by JNA outside the JVM. If that is indeed the case, we wouldn't be able to help you.

**Comment by Daron95** [comment]
Dear @alvdavi 
Here is the hs_err log file
[hs_err_pid1.log](https://github.com/corretto/corretto-21/files/15338474/hs_err_pid1.log)

**Comment by benty-amzn** [comment]
Based on this portion of the stack trace:
```
Stack: [0x00007f7a57f59000,0x00007f7a58059a90],  sp=0x00007f7a58055eb0,  free space=1011k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [jna9211413651637373515.tmp+0x523a]
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.invokeInt(Lcom/sun/jna/Function;JI[Ljava/lang/Object;)I+0
j  com.sun.jna.Function.invoke([Ljava/lang/Object;Ljava/lang/Class;ZI)Ljava/lang/Object;+211
j  com.sun.jna.Function.invoke(Ljava/lang/reflect/Method;[Ljava/lang/Class;Ljava/lang/Class;[Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object;+271
j  com.sun.jna.Library$Handler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+390
j  jdk.proxy2.$Proxy129.argon2i_hash_encoded(Lde/mkammerer/argon2/jna/JnaUint32;Lde/mkammerer/argon2/jna/JnaUint32;Lde/mkammerer/argon2/jna/JnaUint32;[BLde/mkammerer/argon2/jna/Size_t;[BLde/mkammerer/argon2/jna/Size_t;Lde/mkammerer/argon2/jna/Size_t;[BLde/mkammerer/argon2/jna/Size_t;)I+64 jdk.proxy2
j  de.mkammerer.argon2.Argon2i.callLibraryHash([B[BLde/mkammerer/argon2/jna/JnaUint32;Lde/mkammerer/argon2/jna/JnaUint32;Lde/mkammerer/argon2/jna/JnaUint32;[B)I+55
j  de.mkammerer.argon2.BaseArgon2.hashBytes(III[B[B)Ljava/lang/String;+96
j  de.mkammerer.argon2.BaseArgon2.hashBytes(III[B)Ljava/lang/String;+14
j  de.mkammerer.argon2.BaseArgon2.hash(III[CLjava/nio/charset/Charset;)Ljava/lang/String;+16
j  de.mkammerer.argon2.BaseArgon2.hash(III[C)Ljava/lang/String;+9
j  com.qrdn.services.cdtsmgmt.service.passwordhash.HashingPasswordAargon2.hashPassword(Ljava/lang/String;I)Ljava/lang/String;+12
j  com.qrdn.services.cdtsmgmt.controller.CredentialsController.hash(Ljava/lang/Integer;)Ljava/lang/String;+8
```
the issue is happening in a native call to the Argon2 library. 
It's not clear to me what the root cause is. The main possibilities are
- Bug in the JNA bindings for Argon2
- Bug in the Argon2 native library
- Bad data being passed to the lib and the failure not being handled gracefully

**Comment by benty-amzn** [comment]
Looks like this may be the same problem as https://github.com/phxql/argon2-jvm/issues/75 since I see your crash is also on Alpine. There's a couple workarounds suggested in that issue, can you check if those resolve the crash?

**Comment by Daron95** [comment]
@benty-amzn The issue is solved , I used same solution provided by https://github.com/phxql/argon2-jvm/issues/75 by adding "RUN apk add argon2-dev" to the docker file. Thank you!
