### ISSUE TITLE
Licensing question regarding GPL without CPE

### ISSUE THREAD

**Issue by wojteo** [corretto/corretto-21#73]
Hi,

where can I find explanation or proof that would make it clear that files marked as "GNU General Public License version 2 only" are instead released and available to us with Classpath Exception?

One of many examples would be:
https://github.com/corretto/corretto-21/blob/develop/src/hotspot/cpu/arm/gc/g1/g1Globals_arm.hpp

How can I prove that there are no files/components with just "GPL v2" and instead everything is truly on "GPL v2 w/ CPE" ?

**Comment by olivergillespie** [comment]
> How can I prove that there are no files/components with just "GPL v2" and instead everything is truly on "GPL v2 w/ CPE" ?

Don't consider this legal advice, but I think this is not true. Some code is covered by the classpath exception, some is not. The G1GC code you linked is not covered by the exception, it is a plain GPL v2 license. I suppose you'll need legal advice to understand the implications.
