### ISSUE TITLE
Jre 21 for AL2

### ISSUE THREAD

**Issue by mukundhan90** [corretto/corretto-21#74]
Hi, I am looking for rpm from this link - https://docs.aws.amazon.com/corretto/latest/corretto-21-ug/downloads-list.html
to download jre 21 for AL2, can any one share the rpm link to download the same
I tried below but no luck.
ttps://corretto.aws/latest/amazon-corretto-21-x64-al2-jre.rpm

**Comment by benty-amzn** [comment]
Hi, 
JDK 21 was released after Amazon Linux 2 entered rampdown and stopped accepting new packages, so there are no AL2 specific RPMs for Corretto 21. You can try downloading and installing the generic linux RPMs if you need to continue using AL2, or you can try AL2023.

**Comment by mukundhan90** [comment]
Thanks @benty-amzn , this helps

**Comment by mukundhan90** [comment]
> Hi, JDK 21 was released after Amazon Linux 2 entered rampdown and stopped accepting new packages, so there are no AL2 specific RPMs for Corretto 21. You can try downloading and installing the generic linux RPMs if you need to continue using AL2, or you can try AL2023.

Thanks @benty-amzn , this helps.
