### ISSUE TITLE
Corretto GPG key contains invalid signature, `EXPKEYSIG`

### ISSUE THREAD

**Issue by ecpullen** [corretto/corretto-21#82]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here. (You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK and is not specific to Corretto we ask that you raise it to the OpenJDK community. Depending on your contributor status for OpenJDK, please use the [JDK bug system](https://bugs.openjdk.java.net/) or the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo) for the given problem area or [update project](http://mail.openjdk.java.net/mailman/listinfo/jdk-updates-dev).

If your issue is specific to Corretto, then you are in the right place. Please proceed with the following.

### Describe the bug
When installing corretto on ubuntu, the gpg key has invalid signatures.

### To Reproduce
```
wget -O - https://apt.corretto.aws/corretto.key | gpg --dearmor -o /usr/share/keyrings/corretto-keyring.gpg && \
echo "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main" | tee /etc/apt/sources.list.d/corretto.list && apt-get update
```

Error:
```
12.80 Get:1 https://apt.corretto.aws stable InRelease [10.7 kB]
12.83 Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
12.90 Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
12.98 Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
12.98 Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
13.20 Err:1 https://apt.corretto.aws stable InRelease
13.20   The following signatures were invalid: EXPKEYSIG A122542AB04F24E3 Amazon Services LLC (Amazon Corretto release) <corretto-team@amazon.com>
```

### Expected behavior
I expect there to not be an error with the signature.

### Platform information
    OS: Ubuntu
    Version: All versions of corretto.

### Additional context

For VM crashes, please attach the error report file. By default the file name is `hs_err_pidpid.log`, where pid is the process ID of the process.

**Comment by ferjjp** [comment]
Checking the gpg key with something like this ```curl https://apt.corretto.aws/corretto.key | gpg``` gives me an expired date :thinking:. I'm not sure if it's the same key but I would think so

**Comment by davidxia** [comment]
I also see it's expired.

```console
wget -q -O - https://apt.corretto.aws/corretto.key | gpg --show-key  | grep expired
pub   rsa4096/0xA122542AB04F24E3 2019-12-05 [SCEA] [expired: 2024-12-03]
```

**Comment by lutkerd** [comment]
We are working on this and will update in the next couple of hours when the changes are deployed.

**Comment by kumartri** [comment]
Any updates on this one ??

**Comment by lutkerd** [comment]
Updated repo and key has been deployed and the issue should now be resolved.

**Comment by kumartri** [comment]
This one still isn't working for us we are on java 17

**Comment by kumartri** [comment]
W: GPG error: https://apt.corretto.aws/ stable InRelease: The following signatures were invalid: EXPKEYSIG A122542AB04F24E3 Amazon Services LLC (Amazon Corretto release) <corretto-team@amazon.com>
E: The repository https://apt.corretto.aws/ stable InRelease is not signed.
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
W: GPG error: https://dl.google.com/linux/chrome/deb stable InRelease: The following signatures
E: The repository https://dl.google.com/linux/chrome/deb stable InRelease is not signed.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package java-17-amazon-corretto-jdk

**Comment by avocade** [comment]
Still getting this issue but with `java-23-amazon-corretto-jdk`.

**Comment by avocade** [comment]
But seems to have resolved now. Note that you'll need to clear the docker cache. And if that doesn't work, then adding a new step (eg `RUN echo`) above to force it to re-run the jdk download step should do it 👍🏻

**Comment by kumartri** [comment]
We did ran command curl -fsSL https://apt.corretto.aws/corretto.key > /etc/apt/trusted.gpg.d/corretto.asc and echo Force cache invalidation prior to running apt-get update nothing working so far still seeing issue.

**Comment by lutkerd** [comment]
You may need up update the existing key to match the new key in the repo with the following:

```
wget -O - https://apt.corretto.aws/corretto.key | sudo gpg --dearmor -o /usr/share/keyrings/corretto-keyring.gpg && \
echo "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main" | sudo tee /etc/apt/sources.list.d/corretto.list
```

**Comment by seriseyes** [comment]
Having same error with image: maven:3.9-amazoncorretto-17-debian

 RUN apt-get update fails.

**log:** 
`Step 1/9 : FROM maven:3.9-amazoncorretto-17-debian


---> 27279b540c49
Step 2/9 : RUN apt-get update && apt-get install -y openvpn

---> Running in 043381345e1b
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 https://apt.corretto.aws stable InRelease [10.7 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:4 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Err:2 https://apt.corretto.aws stable InRelease The following signatures were invalid: EXPKEYSIG A122542AB04F24E3 Amazon Services LLC (Amazon Corretto release)
Get:5 http://deb.debian.org/debian bookworm/main amd64 Packages [8,789 kB]
Get:6 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [2,712 B]
Get:7 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [206 kB]
Reading package lists...

[91mW: GPG error: https://apt.corretto.aws stable InRelease: The following signatures were invalid: EXPKEYSIG A122542AB04F24E3 Amazon Services LLC (Amazon Corretto release) E: The repository 'https://apt.corretto.aws stable InRelease' is not signed. [0m`
